- name: Set admin password
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Upgrade anti-virus and wildfire
    panos_content:
      ip_address: "{{ ip_address }}"
      password: "{{ password }}"
      anti_virus_update: yes
      wildfire_update: yes
