- name: Restart firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Restart panos device
    panos_restart:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
