- name: Find a security rule
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Find a rule on the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'find'
      rule_name: 'Ansible test 1'
    register: result
  - debug: msg='{{ result.stdout_lines }}'

  - name: Find another test rule on the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'find'
      rule_name: 'Ansible test 2'
    register: result
  - debug: msg='{{ result.stdout_lines }}'
