- name: Delete the test security rules from the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Delete test rule #1 from the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 1'

  - name: Delete test rule #2 from the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 2'

  - name: Delete test rule #3 from the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 3'
