- name: Update some objects on Panorama
  hosts: my-panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Update an object on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'test-address'
      address: '192.168.99.89/25'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      devicegroup: 'shared_services_11022'
      operation: 'update'

  - name: Update a service on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      serviceobject: 'service-xyz'
      protocol: 'tcp'
      destination_port: '9999'
      description: 'This is a test service object'
      devicegroup: 'shared_services_11022'
      operation: 'update'

  - name: Update a tag on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tag_name: 'Test'
      color: 'green'
      description: 'This is test tag'
      devicegroup: 'shared_services_11022'
      operation: 'update'
