- name: Find some objects on Panorama
  hosts: my-panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Find an address object on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'test-address'
      devicegroup: 'shared_services_11022'
      operation: 'find'
    register: result
  - debug: msg='{{ result.stdout_lines }}'

  - name: Find a service on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      serviceobject: 'service-xyz'
      devicegroup: 'shared_services_11022'
      operation: 'find'
    register: result
  - debug: msg='{{ result.stdout_lines }}'

  - name: Find an address group on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressgroup: 'test-address-group'
      devicegroup: 'shared_services_11022'
      operation: 'find'
    register: result
  - debug: msg='{{ result.stdout_lines }}'

  - name: Find a tag on Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tag_name: 'Test'
      devicegroup: 'shared_services_11022'
      operation: 'find'
    register: result
  - debug: msg='{{ result.stdout_lines }}'
