- name: Find sone security rules in Panorama
  hosts: my-panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Find a rule on Panorama
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'find'
      rule_name: 'Ansible test 1'
      devicegroup: 'shared_services_11022'
    register: result
  - debug: msg='{{ result.stdout_lines }}'

  - name: Find another test rule on Panorama
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'find'
      rule_name: 'Ansible test 2'
      devicegroup: 'shared_services_11022'
    register: result
  - debug: msg='{{ result.stdout_lines }}'
